// 4ac1376b9f55f4b738062841432d205364984c99
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "1.1.0pre-iOS"
#define GIT_HASH "4ac1376b9f55f4b738062841432d205364984c99"
#define GIT_TIME "2021-08-01 11:24:47 +1000"
